### ISSUE TITLE
label at bottom of triptic

### ISSUE THREAD

**Issue by bbest** [marinebon/fk-esr-info#12]
Per [Florida Keys National Marine Sanctuary Integrated Ecosystem Assessment Conceptual Model.docx - Google Docs](https://docs.google.com/document/d/17vNGIiqBB94oueIhSt7ZVd9w4xj1Hpkc/edit):

![image](https://user-images.githubusercontent.com/2837257/109693982-22af4500-7b3f-11eb-963e-7f3074217d30.png)

**Comment by bbest** [comment]
This could be done in at least a couple ways:

- table with 3 cells
- div tags with Bootstrap 4 layout

See also https://github.com/marinebon/fk-esr-info/issues/11#issuecomment-789142509

**Comment by superjai** [comment]
[Infographic.html](https://marinebon.org/fk-esr-info/infographic.html) now contains the labels, as you can see below, contained within a html table.

![caption](https://user-images.githubusercontent.com/1744300/111262890-5be5bb80-85fb-11eb-85a5-29ade39b65c8.png)

You will notice that the triptych labels are slightly offset to the left of the image. This is due to some complexity in the css layout that I am unable as yet to sort out. 

Similarly, the attribution on the last line is also way to the right, for the same reason.

Perhaps this is good enough, but if not, more css hacking is needed.

**Comment by superjai** [comment]
The layout is now fixed

![caption2](https://user-images.githubusercontent.com/1744300/111383604-d572bd80-867e-11eb-8e28-2445c21cb8cd.png)

**Comment by bbest** [comment]
My slight preference is for these to be above rather than below infographic, but closing because this is what Kelly M requested.
